---
- name: install python newest version
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Copy python.sh script to remote hosts
      ansible.builtin.copy:
        src: /home/ansible/script/python.sh
        dest: /home/ansible/script/python.sh
        owner: ansible
        group: ansible
        mode: "0700"

    - name: Run python script
      ansible.builtin.command: "$HOME/script/python.sh"
