---
- name: Install dependencies
  block:
    - name: (CentOS/RHEL 8) Install dependencies
      ansible.builtin.yum:
        name: "{{ packages }}"
        update_cache: true
        state: present
      vars:
        packages:
          - platform-python
          - iptables-ebtables
          - ipset
          - iptables
          - python3-firewall
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] is version('8', '==')

- name: install firewalld
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Start firewall service
  ansible.builtin.service:
    name: firewalld
    state: started

- name: enable firewalld
  ansible.builtin.service:
    name: firewalld
    enabled: true

- name: allow http traffic
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: allow https traffic
  ansible.posix.firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled

- name: allow port
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    immediate: true
    state: enabled

- name: allow port
  ansible.posix.firewalld:
    port: 443/tcp
    permanent: true
    immediate: true
    state: enabled
