---
- name: install nginx on redhat
  import.tasks: redhat.yaml
  when: ansible_facts['os_family'] | lower == "redhat"

- name: install nginx on Debian
  import.tasks: debian.yaml
  when: ansible_facts['os_family'] | lower == "debian"
